[build]
  environment = { PYTHON_VERSION = "3.11" }
[[headers]]
  for = "**/*.part"
    [headers.values]
        Content-Type = "text/xml; charset=utf-8"
[[headers]]
  for = "**/*.index"
    [headers.values]
        Content-Type = "text/xml; charset=utf-8"
